### ISSUE TITLE
OpenAPI Componentizer

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#10]
Summary: Take any OpenAPI 3.x definition and loop through and move common properties to be centralized components. Using the components object to centralize and reuse schema, parameters, examples, and other elements of an API. Allowing for more efficient and reusable OpenAPI definitions that maximize the components object of the specification.

Skills: Familiarity with the OpenAPI specification.

**Comment by jansche** [comment]
This is a potential child project within OAI. Will migrate it and then put in some questions.
