### ISSUE TITLE
Autogenerate Contract Test Collections

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#11]
Summary: Generate a Postman collection for an OpenAPI definition, looping through each available path operation and then generating a corresponding request in a Postman collection, and automate the creation of a test script for the path operations contract, using the schema referenced and validating the response, media type, and resulting JSON Schema.

**Skills:** Familiarity with Postman, the OpenAPI specification, and node.js programming.

**Expected Outcomes:** An open-source solution that will parse any OpenAPI and generate a Postman collection that tests each individual API operation and validates the contract for the response using the JSON schema defined in the OpenAPI definition--using OpenAPI as a contract, but testing it using the open-source Postman collection format and test scripts.

**Possible mentors:**  Mentors are still being determined and will be assigned to projects based upon availability.

**Size of Project:** 60-80 hours

**Rating:** Medium skills level

**Comment by jansche** [comment]
Not ready to be a 2023 GSoC project. Postman Collections are a public repo, but would probably not qualify at them moment for participation.
> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.
