### ISSUE TITLE
Github OpenAPI Search

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#12]
Summary: Provide a robust yet easy way to search Github for Swagger and OpenAPI definitions. Understanding that there is a lot of noise available, that we only care about OpenAPIs that validate, and that the Github API has rate limits that require you to automate the crawling over time. Providing a robust open-source solution that will crawl public Github repositories for machine-readable API definitions.

**Skills:** Knowledge of the Github API, and the OpenAPI specification.

**Expected Outcomes:** An open-source API that allows you to pass in search parameters and then utilize the GitHub API to perform the search, helping simplify the search interface, make rate limits visible as part of the response, and handle conducting a search in an asynchronous way, allowing the user to make a call to initiate, but then separate calls to receive results over time as results come in, helping show outcomes over time.

**Possible mentors:**  Mentors are still being determined and will be assigned to projects based upon availability.

**Size of Project:** 30-40 hours

**Rating:** Lower skills level

**Comment by jansche** [comment]
This is a potential child project within OAI. Will migrate it and then put in some questions.
