### ISSUE TITLE
OpenAPI Web Search

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#13]
Summary: Develop an open-source approach to finding Swagger and OpenAPI definitions on the open web, crawling web pages looking for API definitions, validating them, and them consuming and indexing them as part of an ongoing search. Providing a simple way that developers can find APIs that exist by finding documentation, repositories, and other common aspects of running an API.

**Skills:** Knowledge of the web, and how to crawl web pages, follow URLs, or utilize an existing solution like Common Crawl.

**Expected Outcomes:** Provide a simple open-source API that abstracts away the complexity of searching the web for specific terms, helping identify APIs in a sea of web pages. Providing a simple interface that will set in motion an asynchronous searching of the web or corpus of web content looking for APIs. Allowing users to initiate a search, but then return regularly to see the results of the search over time, building up results, but then aggregating them for each pulling via simple API.

**Possible mentors:**  Mentors are still being determined and will be assigned to projects based upon availability.

**Size of Project:** 60-80 hours

**Rating:** Medium skills level

**Comment by jansche** [comment]
This is a potential child project within OAI. Will migrate it and then put in some questions.
