### ISSUE TITLE
Schema.org OpenAPI Catalog

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#14]
**Summary:** Create an open catalog of OpenAPI definitions for each of the Schema.org objects. Providing a robust set of starting OpenAPI templates for teaching or developing new APIs using a design-first approach. Helping save developers work when it comes to starting new APIs, but also help ensure APIs are developed using common standards and are as interoperable as possible.

**Skills:** Familiarity with the OpenAPI specification, and Schema.org objects.

**Expected Outcomes:** A public repository of up-to-date OpenAPI 3.1 definitions for each of the Schema.org objects. Bonus points if you share your code used to generate the OpenAPI definitions, allowing them to be updated as objects evolve.

**Possible mentors:** Mentors are still being determined and will be assigned to projects based upon availability.

**Size of Project:** 60-80 hours

**Rating:** Medium skills level

**Comment by jansche** [comment]
This is a potential child project within OAI. Will migrate it and then put in some questions.
