### ISSUE TITLE
Platform SDK

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#18]
An SDK providing utilities to perform distribution chores required in the API lifecycle. To start with, focus can be towards providing APIs to help developers manage their build phase of APIs.

**Expectation**

- Easy interface to configure and make releases (over git)
- Ability to package source code (popular languages) to Docker images
- Helps to export packaged artifacts to configurable destinations (AWS, GCP)
- Utility to maintain and upgrade internal org’s docker images

**Knowledge Required**
Hands-on experience with Git and Docker is necessary. 

Note for internal team:

- This can be extended to be used as Integrations in Postman ecosystem
- This SDK will contain few features that Vulcan provides but in a more generic and configurable way. Moving ahead, Vulcan can utilise the above SDK to create a win-win ecosystem.
- For now, we can focus towards Build phase of API Distribution lifecycle.

**Comment by jansche** [comment]
This seems to be a standalone project not tied to any existing OS project. Would likely not qualify for GSoC 2023, so not migrating it to the new 2023 repo.
