### ISSUE TITLE
$ref Resolver for OpenAPI documents

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#2]
Summary
Provide a robust solution for following all $ref and assembling as a single document for use at run or build time. Addressing different relative and remote paths, allowing OpenAPI definitions to be managed in an atomic way, but then assembled for use in publishing documentation, generating mock services, testing, and other lifecycle needs.

Skills:
Need basic understanding of OpenAPI, and JSON Schema.

**Comment by Relequestual** [comment]
I'm happy to help with this in any way that I can.

**Comment by jansche** [comment]
This is a potential child project within OAI. Will migrate it to 2023 and then put in some questions.
