### ISSUE TITLE
Quantify Scope of API Specification Communities

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#6]
Summary: Quantify the scope of the OpenAPI, AsyncAPI, JSON Schema GraphQL, and gRPC communities. Using publicly available data points like Twitter, Github, StackOverflow, web search, and other characteristics of the existing communities behind these specifications, how do we measure the size, scope, and participation of each of these communities. While also working to compare them in some way to understand how they are different or the same.

Skills: Ability to pull information from APIs, scraping, and analyze either programmatically or via spreadsheet, Airtable, or another mechanism, then be able to visualize and make sense of in a useful way.

**Comment by jansche** [comment]
Not ready to be a 2023 GSoC project. Postman Collections are a public repo, but would probably not qualify at them moment for participation.
> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.
