### ISSUE TITLE
OpenAPI Diff

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#7]
Summary: Provide a simple, but OpenAPI specific diff tool that will creatively and intuitively show the difference between two separate OpenAPI documents. Providing object-specific considerations that are unique to the OpenAPI specification. Helping understand changes, but also focus in on breaking changes that will cause the most negative impact.

Skills: Base understanding of the OpenAPI specification.

**Comment by jansche** [comment]
This is a very small but potential child project within OAI. Will migrate it to 2023 and then put in some questions.

**Comment by jansche** [comment]
This is a very small but potential child project within OAI. Will migrate it to 2023 and then put in some questions.
