### ISSUE TITLE
Postman Collection Script Manger

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/gsoc-2022#9]
Summary: Provide an open-source solution for aggregating and managing scripts across all of a team's Postman collections. Using Git or the Postman API to pull many collections, organize the scripts, and allow for easier indexing, managing, editing, and publishing of pre-request and test scripts that exist as part of the Postman collection format. Providing a simple, open-source way for developers to manage scripts across many different APis.

Skill: Familiarity with Postman, collections, and Node.js scripting.

**Comment by jansche** [comment]
Not ready to be a 2023 GSoC project. Postman Collections are a public repo, but would probably not qualify at them moment for participation.
> open source projects wishing to apply need to have a solid community; the goal of GSoC is to bring new contributors into established and welcoming communities. While you don’t have to have 50+ community members, the project also can’t have as few as three people.
